server:
  port: 8080

# log
logging:
  level:
    com:
      operatorTracker: debug
    org:
      springframework: warn
  path: logs/app-api

# MyBatis
mybatis:
  typeAliasesPackage: com.operatorTracker.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:23306/operatortrackerdb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    username: operatortrackeruser
    password: 123456

